import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog"; import { Building2, Plus, Search, Pencil, Trash2, Loader2 } from "lucide-react"; import { toast } from "sonner";
type Institution={id:string;name:string;type:string|null;city:string|null;contact_email:string|null;contact_phone:string|null;active:boolean};
const empty={name:"",type:"Universidad",city:"",contact_email:"",contact_phone:""};
export default function InstitutionsManager(){const [rows,setRows]=useState<Institution[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[editing,setEditing]=useState<Institution|null>(null),[form,setForm]=useState(empty);
const load=async()=>{const {data,error}=await supabase.from("institutions").select("*").order("name");if(error) toast.error(error.message); else setRows((data||[]) as Institution[])};useEffect(()=>{load()},[]);
const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);const payload={...form,active:true};const r=editing?await supabase.from("institutions").update(payload).eq("id",editing.id):await supabase.from("institutions").insert(payload);setSaving(false);if(r.error)return toast.error(r.error.message);toast.success(editing?"Institución actualizada":"Institución registrada");setOpen(false);setEditing(null);setForm(empty);load()};
const edit=(x:Institution)=>{setEditing(x);setForm({name:x.name,type:x.type||"Universidad",city:x.city||"",contact_email:x.contact_email||"",contact_phone:x.contact_phone||""});setOpen(true)};
const del=async(id:string)=>{if(!confirm("¿Eliminar esta institución y su estructura de repositorio?"))return;const {error}=await supabase.from("institutions").delete().eq("id",id);if(error)toast.error(error.message);else{toast.success("Institución eliminada");load()}};
const filtered=rows.filter(x=>`${x.name} ${x.city||""} ${x.type||""}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-bold text-slate-900">Instituciones</h2><p className="mt-1 text-sm text-slate-500">Registra las instituciones con las que Educalidad mantiene procesos de acompañamiento.</p></div><Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v){setEditing(null);setForm(empty)}}}><DialogTrigger asChild><Button className="bg-amber-300 hover:bg-amber-200"><Plus className="mr-2 h-4 w-4"/>Nueva institución</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{editing?"Editar institución":"Registrar institución"}</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-4"><div><Label>Nombre *</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="grid sm:grid-cols-2 gap-4"><div><Label>Tipo</Label><Input value={form.type} onChange={e=>setForm({...form,type:e.target.value})}/></div><div><Label>Ciudad</Label><Input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div></div><div><Label>Correo de contacto</Label><Input type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></div><div><Label>Teléfono</Label><Input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div><Button disabled={saving} className="bg-slate-950">{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{editing?"Guardar cambios":"Registrar institución"}</Button></form></DialogContent></Dialog></div>
<div className="relative max-w-lg"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="pl-9" placeholder="Buscar institución..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="hidden grid-cols-[1.4fr_.7fr_.7fr_1fr_auto] gap-4 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wider text-slate-500 md:grid"><span>Institución</span><span>Tipo</span><span>Ciudad</span><span>Contacto</span><span>Acciones</span></div>{filtered.length===0?<div className="p-10 text-center text-slate-500">No hay instituciones registradas.</div>:filtered.map(x=><div key={x.id} className="grid gap-3 border-t px-5 py-4 first:border-t-0 md:grid-cols-[1.4fr_.7fr_.7fr_1fr_auto] md:items-center"><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-950/10 p-2"><Building2 className="h-5 w-5 text-slate-950"/></div><span className="font-semibold">{x.name}</span></div><span className="text-sm text-slate-600">{x.type||"—"}</span><span className="text-sm text-slate-600">{x.city||"—"}</span><span className="text-sm text-slate-600 break-all">{x.contact_email||x.contact_phone||"—"}</span><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={()=>edit(x)}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>del(x.id)}><Trash2 className="h-4 w-4 text-red-500"/></Button></div></div>)}</div></div>}
