import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { CalendarDays, Mail, MessageCircle, Send } from "lucide-react";

const SERVICES = ["Asesoría en procesos de autoevaluación y acreditación","Plataforma para la gestión de la autoevaluación y acreditación","Acompañamiento integral con asesoría, plataforma y soporte","Asesoría personalizada y apoyo en la elaboración de evidencias"];
const PROCESS_TYPES=["Institucional","Carrera","Programa de posgrado"];
const COMPANY_EMAIL="infoeducalidadsas@gmail.com";
const WHATSAPP_NUMBER="593969628650"; // Completar antes de publicar. Ej.: 593991234567

const empty={nombres:"",institucion:"",cargo:"",correo:"",telefono:"",servicio:"",tipoProceso:"",agenciaModelo:"",mensaje:""};
const ContactForm=()=>{
 const [sending,setSending]=useState(false); const [formData,setFormData]=useState(empty);
 useEffect(()=>{const apply=(service?:string)=>service&&setFormData(v=>({...v,servicio:service})); apply(sessionStorage.getItem("educalidad:selectedService")||undefined); const h=(e:Event)=>apply((e as CustomEvent<string>).detail); window.addEventListener("educalidad:service-selected",h); return()=>window.removeEventListener("educalidad:service-selected",h)},[]);
 const change=(key:keyof typeof empty,value:string)=>setFormData(v=>({...v,[key]:value}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(!formData.nombres||!formData.institucion||!formData.correo||!formData.servicio||!formData.tipoProceso||!formData.mensaje){toast.error("Por favor complete los campos requeridos.");return;} setSending(true); try{await new Promise(r=>setTimeout(r,400)); toast.success("Consulta recibida. Nos pondremos en contacto con usted."); setFormData(empty); sessionStorage.removeItem("educalidad:selectedService");}catch(err:any){toast.error(err?.message||"No se pudo enviar la consulta.")}finally{setSending(false)}};
 return <section id="contacto" className="py-24 md:py-32 px-4 bg-background scroll-mt-24"><div className="container mx-auto max-w-6xl"><div className="text-center mb-12"><p className="text-sm font-semibold text-primary uppercase tracking-[.18em] mb-3">Contáctenos</p><h2 className="text-4xl md:text-5xl font-semibold tracking-[-.03em]">Conversemos sobre las necesidades de su institución</h2><p className="text-lg text-muted-foreground max-w-3xl mx-auto mt-4">Escríbanos o agende una cita virtual para conocer su proceso, identificar sus necesidades y coordinar una propuesta de acompañamiento.</p></div>
 <div className="grid lg:grid-cols-5 rounded-none border overflow-hidden"><aside className="lg:col-span-2 p-7 md:p-8 bg-secondary/20 border-b lg:border-b-0 lg:border-r"><h3 className="text-xl font-semibold">Canales de contacto</h3><div className="mt-6 space-y-4 text-sm"><a href={`mailto:${COMPANY_EMAIL}`} className="flex gap-3 items-center hover:text-primary"><Mail className="h-5 w-5 text-primary"/><span>{COMPANY_EMAIL}</span></a><button type="button" onClick={()=>WHATSAPP_NUMBER?window.open(`https://wa.me/${WHATSAPP_NUMBER}`,"_blank"):toast.info("Complete el número de WhatsApp de la empresa antes de publicar.")} className="flex gap-3 items-center text-left hover:text-primary"><MessageCircle className="h-5 w-5 text-primary"/><span>{WHATSAPP_NUMBER?"Contactar por WhatsApp":"[número de contacto]"}</span></button><button type="button" onClick={()=>document.getElementById("agenda")?.scrollIntoView({behavior:"smooth"})} className="flex gap-3 items-center text-left hover:text-primary"><CalendarDays className="h-5 w-5 text-primary"/><span>Agendar una cita virtual</span></button></div><div className="mt-8 border-t pt-6 text-sm text-muted-foreground"><p><strong className="text-foreground">Horario de atención:</strong> Lunes a Viernes: 8:00 am - 8:00 pm (UTC -5:00)</p></div></aside>
 <div className="lg:col-span-3 p-7 md:p-8"><h3 className="text-xl font-semibold mb-6">Formulario de consulta</h3><form onSubmit={submit} className="space-y-5"><div className="grid md:grid-cols-2 gap-4"><Field label="Nombre y apellido *"><Input value={formData.nombres} onChange={e=>change("nombres",e.target.value)} required/></Field><Field label="Institución o empresa *"><Input value={formData.institucion} onChange={e=>change("institucion",e.target.value)} required/></Field><Field label="Cargo"><Input value={formData.cargo} onChange={e=>change("cargo",e.target.value)}/></Field><Field label="Correo electrónico *"><Input type="email" value={formData.correo} onChange={e=>change("correo",e.target.value)} required/></Field><Field label="Teléfono o WhatsApp"><Input type="tel" value={formData.telefono} onChange={e=>change("telefono",e.target.value)}/></Field><Field label="Servicio de interés *"><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={formData.servicio} onChange={e=>change("servicio",e.target.value)} required><option value="">Seleccione...</option>{SERVICES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Tipo de proceso *"><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={formData.tipoProceso} onChange={e=>change("tipoProceso",e.target.value)} required><option value="">Seleccione...</option>{PROCESS_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Agencia o modelo de evaluación"><Input value={formData.agenciaModelo} onChange={e=>change("agenciaModelo",e.target.value)} placeholder="Si ya está definido"/></Field></div><Field label="Mensaje *"><Textarea rows={5} value={formData.mensaje} onChange={e=>change("mensaje",e.target.value)} placeholder="Cuéntenos qué necesita y en qué etapa se encuentra" required/></Field><Button type="submit" variant="accent" size="lg" className="w-full" disabled={sending}>{sending?"Enviando...":<><Send className="h-4 w-4 mr-2"/>Enviar consulta</>}</Button></form></div></div>
 <p className="text-xs text-muted-foreground mt-4 text-center">Nota técnica: este componente conserva el envío simulado del formulario original. Debe conectarse a su servicio de correo o Edge Function antes de publicar.</p></div></section>
};
const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-2"><Label>{label}</Label>{children}</div>;
export default ContactForm;
