import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowRight, BadgeCheck, CheckCircle2, ClipboardCheck, Layers3, FilePenLine } from "lucide-react";
import servicesBg from "@/assets/services-bg.jpg";

const services = [
  { icon: ClipboardCheck, eyebrow: "Estrategia y metodología", title: "Asesoría en procesos de autoevaluación y acreditación", description: "Acompañamiento especializado para orientar a su equipo en cada etapa del proceso, desde el diagnóstico hasta la preparación para la evaluación externa.", cta: "Solicitar asesoría", items: [
    ["Diagnóstico inicial", "Revisión de la situación de la institución, carrera o programa para identificar avances, necesidades y prioridades."], ["Interpretación del modelo de evaluación", "Orientación sobre criterios, estándares, indicadores y evidencias solicitadas por el CACES o la agencia internacional correspondiente."], ["Planificación del proceso", "Apoyo en la definición de actividades, responsables, plazos y cronograma de trabajo."], ["Orientación al equipo de autoevaluación", "Sesiones de asesoría para comprender los requerimientos y coordinar el trabajo de las áreas participantes."], ["Revisión de evidencias", "Análisis de la pertinencia, coherencia y suficiencia de los documentos que respaldan cada indicador."], ["Apoyo en el informe de autoevaluación", "Orientación para estructurar respuestas, analizar resultados y presentar información sustentada."], ["Planes de mejora", "Acompañamiento en la formulación de objetivos, actividades, indicadores, responsables y evidencias de cumplimiento."], ["Preparación para la evaluación externa", "Apoyo en la organización de información, reuniones y presentación de evidencias para la visita de pares evaluadores."] ] },
  { icon: Layers3, eyebrow: "Tecnología para la calidad", title: "Plataforma para la gestión de la autoevaluación y acreditación", description: "Centralice la información, coordine a sus equipos y consulte el avance del proceso en tiempo real mediante una estructura alineada al modelo de evaluación.", cta: "Solicitar una demostración", items: [
    ["Configuración del modelo de evaluación", "Organización de la plataforma según la agencia y el proceso de acreditación seleccionado."], ["Edición de modelos", "Creación y actualización de criterios, estándares, indicadores y requerimientos de evidencias mediante permisos autorizados."], ["Organización por unidad evaluada", "Gestión diferenciada de la información correspondiente a cada institución, carrera o programa."], ["Carga y clasificación de evidencias", "Incorporación de documentos y enlaces por criterio e indicador, manteniendo su trazabilidad."], ["Responsables, roles y permisos", "Distribución de tareas y definición de usuarios autorizados para cargar, revisar, validar o consultar información."], ["Revisión y validación", "Registro de observaciones y seguimiento de evidencias pendientes, revisadas o aprobadas."], ["Respuestas por indicador", "Espacios para registrar análisis, justificaciones, fortalezas y oportunidades de mejora."], ["Consulta y notificaciones", "Visualización de información en tiempo real y avisos sobre tareas, plazos y observaciones."], ["Dashboard de seguimiento", "Avance por carrera, programa, criterio, indicador y responsable."], ["Dashboard para evaluadores externos", "Presentación ordenada de información académica, indicadores y documentos según el modelo aplicable."], ["Invitación a pares evaluadores", "Acceso autorizado para consultar la información y evidencias del proceso."], ["Capacitación y soporte técnico", "Orientación para utilizar la plataforma y atención de consultas sobre su funcionamiento."] ] },
  { icon: BadgeCheck, eyebrow: "Solución 360°", title: "Acompañamiento integral con asesoría, plataforma y soporte", description: "Una solución integral que articula acompañamiento metodológico, gestión tecnológica y soporte durante las etapas acordadas del proceso.", cta: "Solicitar una propuesta integral", items: [
    ["Diagnóstico y definición del alcance", "Identificación de las necesidades de la institución, carrera o programa y de las etapas que requieren acompañamiento."], ["Plan de trabajo personalizado", "Definición de actividades, entregables, responsables y tiempos de ejecución."], ["Implementación de la plataforma", "Configuración del modelo, unidades evaluadas, usuarios y permisos."], ["Capacitación del equipo", "Preparación de responsables, revisores y coordinadores para desarrollar la autoevaluación y utilizar la plataforma."], ["Gestión de evidencias", "Orientación para recopilar, organizar, revisar y validar los respaldos de cada indicador."], ["Apoyo documental", "Asistencia en la elaboración y revisión de informes, matrices y otros documentos necesarios."], ["Seguimiento del proceso", "Reuniones para revisar avances, resolver consultas y coordinar acciones pendientes."], ["Informe de autoevaluación", "Revisión de la coherencia entre respuestas, resultados y evidencias presentadas."], ["Gestión de planes de mejora", "Apoyo en su formulación y seguimiento mediante la plataforma."], ["Preparación para la visita de pares", "Organización de evidencias, accesos y presentación de información para la evaluación externa."], ["Atención de observaciones", "Orientación para organizar respuestas y respaldos frente a requerimientos de la agencia."], ["Soporte personalizado", "Atención técnica y metodológica durante las etapas acordadas del servicio."] ] },
  { icon: FilePenLine, eyebrow: "Soporte documental", title: "Asesoría personalizada y apoyo en la elaboración de evidencias", description: "Atención específica para resolver necesidades documentales y metodológicas, reforzar la trazabilidad y presentar evidencias consistentes con el modelo aplicable.", cta: "Agendar una asesoría personalizada", items: [
    ["Identificación de evidencias necesarias", "Orientación sobre los documentos que respaldan cada criterio, estándar o indicador."], ["Elaboración de informes", "Apoyo para estructurar y redactar informes técnicos, académicos y de gestión a partir de información institucional verificable."], ["Diseño de matrices", "Preparación de matrices de evidencias, trazabilidad, alineación, seguimiento y cumplimiento."], ["Apoyo en actas y registros", "Orientación para documentar reuniones, socializaciones, acuerdos y actividades realizadas."], ["Elaboración de planes de mejora", "Apoyo para definir acciones, metas, indicadores, responsables, plazos y medios de verificación."], ["Revisión de documentos existentes", "Análisis de claridad, coherencia, pertinencia y correspondencia con el modelo de evaluación."], ["Organización de respaldos", "Orientación para clasificar, identificar y vincular documentos con los indicadores correspondientes."], ["Atención de consultas específicas", "Sesiones para resolver dudas sobre requerimientos, respuestas y presentación de evidencias."], ["Acompañamiento a medida", "Definición del servicio según los documentos, actividades o etapas que su equipo necesita atender."] ] },
];

const selectService = (service: string) => { sessionStorage.setItem("educalidad:selectedService", service); window.dispatchEvent(new CustomEvent("educalidad:service-selected", { detail: service })); document.getElementById("contacto")?.scrollIntoView({ behavior: "smooth", block: "start" }); };

const Services = () => {
  const [active, setActive] = useState(0);
  const [direction, setDirection] = useState<"left" | "right">("right");
  const go = (next: number) => { setDirection(next > active || (active === services.length - 1 && next === 0) ? "right" : "left"); setActive((next + services.length) % services.length); };
  const previous = () => go((active - 1 + services.length) % services.length);
  const next = () => go((active + 1) % services.length);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "ArrowLeft") previous(); if (e.key === "ArrowRight") next(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [active]);
  const service = services[active];
  return (
    <section id="servicios" className="relative scroll-mt-24 overflow-hidden bg-white py-24 px-4 md:py-32" style={{ backgroundImage: `linear-gradient(rgba(255,255,255,.965),rgba(255,255,255,.965)), url(${servicesBg})`, backgroundSize: "cover", backgroundPosition: "center" }}>
      <div className="absolute -left-32 top-20 h-72 w-72 rounded-full bg-primary/5 blur-3xl"/><div className="absolute -right-32 bottom-10 h-80 w-80 rounded-full bg-primary/5 blur-3xl"/>
      <div className="container relative mx-auto max-w-7xl">
        <div className="mx-auto mb-14 max-w-4xl text-center"><p className="mb-3 text-xs font-bold uppercase tracking-[.28em] text-primary">Servicios especializados</p><h2 className="text-4xl font-semibold tracking-[-.035em] text-slate-950 md:text-6xl">Soluciones para cada etapa de la acreditación</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">Integramos metodología, gestión documental y tecnología para acompañar a instituciones de educación superior, carreras y programas de posgrado en procesos nacionales ante el CACES y en procesos internacionales con agencias acreditadoras.</p></div>
        <div className="relative mx-auto max-w-6xl px-0 md:px-14">
          <button type="button" onClick={previous} aria-label="Servicio anterior" className="absolute left-0 top-1/2 z-20 hidden h-12 w-12 -translate-y-1/2 items-center justify-center rounded-full border bg-background shadow-lg transition hover:-translate-x-1 hover:border-primary/40 hover:text-primary md:flex"><ArrowLeft className="h-5 w-5"/></button>
          <button type="button" onClick={next} aria-label="Servicio siguiente" className="absolute right-0 top-1/2 z-20 hidden h-12 w-12 -translate-y-1/2 items-center justify-center rounded-full border bg-background shadow-lg transition hover:translate-x-1 hover:border-primary/40 hover:text-primary md:flex"><ArrowRight className="h-5 w-5"/></button>
          <article key={active} className={`overflow-hidden border border-slate-200 bg-white shadow-[0_35px_90px_-45px_rgba(15,23,42,.35)] animate-in fade-in duration-300 ${direction === "right" ? "slide-in-from-right-4" : "slide-in-from-left-4"}`}>
            <div className="grid lg:grid-cols-[.8fr_1.2fr]">
              <div className="relative overflow-hidden border-b bg-slate-950 p-7 text-white md:p-10 lg:border-b-0 lg:border-r lg:p-12"><div className="absolute right-0 top-0 h-48 w-48 translate-x-1/3 -translate-y-1/3 rounded-full bg-primary/10"/><div className="relative"><div className="mb-8 flex items-center justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-300 text-slate-950 shadow-sm"><service.icon className="h-7 w-7"/></div><span className="text-sm font-semibold tabular-nums text-muted-foreground">{String(active + 1).padStart(2,"0")} <span className="mx-1 opacity-40">/</span> {String(services.length).padStart(2,"0")}</span></div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-amber-300">{service.eyebrow}</p><h3 className="text-3xl font-bold leading-tight tracking-tight text-white">{service.title}</h3><p className="mt-5 leading-relaxed text-slate-300">{service.description}</p><div className="mt-8"><Button variant="accent" size="lg" onClick={() => selectService(service.title)}>{service.cta}<ArrowRight className="ml-2 h-4 w-4"/></Button></div><div className="mt-9 border-t pt-6"><p className="text-xs uppercase tracking-[.18em] text-slate-400">Enfoque</p><p className="mt-2 text-sm font-medium text-slate-200">Rigor metodológico · Evidencia trazable · Mejora continua</p></div></div></div>
              <div className="p-7 md:p-10 lg:p-12"><div className="mb-7 flex items-center gap-3"><span className="h-px w-8 bg-primary"/><p className="text-sm font-semibold">Este servicio incluye</p></div><div className="grid gap-x-8 gap-y-5 md:grid-cols-2">{service.items.map(([title,text]) => <div key={title} className="group flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary"/><p className="text-sm leading-relaxed"><strong className="font-semibold text-foreground">{title}. </strong><span className="text-muted-foreground">{text}</span></p></div>)}</div></div>
            </div>
          </article>
          <div className="mt-6 flex items-center justify-between gap-4 md:justify-center"><button onClick={previous} className="flex h-11 w-11 items-center justify-center rounded-full border bg-background md:hidden" aria-label="Anterior"><ArrowLeft className="h-5 w-5"/></button><div className="flex items-center gap-2">{services.map((s,i)=><button key={s.title} onClick={()=>go(i)} aria-label={`Ver servicio ${i+1}`} className={`h-2.5 rounded-full transition-all ${i===active ? "w-8 bg-primary" : "w-2.5 bg-border hover:bg-primary/40"}`}/>)}</div><button onClick={next} className="flex h-11 w-11 items-center justify-center rounded-full border bg-background md:hidden" aria-label="Siguiente"><ArrowRight className="h-5 w-5"/></button></div>
        </div>
        <p className="mx-auto mt-10 max-w-3xl text-center text-sm leading-relaxed text-muted-foreground">El alcance, los entregables y la duración se definen mediante una propuesta ajustada al modelo de evaluación, la etapa del proceso y las necesidades de cada institución.</p>
      </div>
    </section>
  );
};
export default Services;
