import { Award, GraduationCap, Linkedin, Mail, Quote } from "lucide-react";
const team = [
  { name:"Andrea Alejandra Cujilan Guaman", role:"Master Universitario en Dirección en la Gestión Pública", specialty:"Especialista en aseguramiento de la calidad y procesos de evaluación en educación superior.", credential:"Credencial / certificación como evaluadora o acreditadora", experience:"Agregue aquí una síntesis de su experiencia relevante en evaluación, autoevaluación, acreditación, planificación o gestión universitaria.", image:"/team/profesional-1.jpeg", email:"", linkedin:"https://www.linkedin.com/in/andrea-cujilan-9a3b439b" },
  { name:"Vanessa Olimpia Rodriguez Flores", role:"Magister en Contabilidad y Auditoría con mención en Gestión Tributaria", specialty:"Especialista en gestión académica, evidencias, mejora continua y acompañamiento institucional.", credential:"Credencial / certificación como evaluadora o acreditadora", experience:"Agregue aquí una síntesis de su experiencia relevante y los ámbitos en los que acompaña a instituciones, carreras o programas.", image:"/team/profesional-2.jpeg", email:"", linkedin:"" },
];
const Team=()=> <section id="equipo" className="scroll-mt-24 overflow-hidden bg-slate-950 px-4 py-24 text-white md:py-32">
  <div className="container mx-auto max-w-7xl">
    <div className="grid gap-8 border-b border-white/10 pb-12 lg:grid-cols-2 lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-amber-300">Nuestro equipo</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.035em] md:text-6xl">Experiencia profesional detrás de cada proceso.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-300">La metodología importa, pero también quién acompaña las decisiones. Nuestro equipo integra experiencia en educación superior, lectura técnica de modelos y gestión de evidencias.</p></div>
    <div className="mt-14 grid gap-8 lg:grid-cols-2">{team.map((p,i)=><article key={p.name} className="group relative overflow-hidden border border-white/10 bg-white/[.04]">
      <div className="grid min-h-[570px] sm:grid-cols-[.82fr_1.18fr]">
        <div className="relative min-h-[380px] overflow-hidden bg-slate-900 sm:min-h-full"><img src={p.image} alt={p.name} onError={(e)=>{e.currentTarget.src="/placeholder.svg"}} className="absolute inset-0 h-full w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent"/><span className="absolute left-5 top-5 text-6xl font-light text-white/15">0{i+1}</span></div>
        <div className="flex flex-col p-7 md:p-9"><Quote className="h-7 w-7 text-amber-300"/><p className="mt-7 text-xs font-bold uppercase tracking-[.18em] text-amber-300">Profesional Educalidad</p><h3 className="mt-3 text-3xl font-semibold tracking-tight">{p.name}</h3><div className="mt-4 flex gap-3 text-sm text-slate-300"><GraduationCap className="mt-0.5 h-4 w-4 shrink-0 text-amber-300"/><span>{p.role}</span></div><p className="mt-6 text-sm leading-7 text-slate-300">{p.specialty}</p>
        <div className="my-7 border-y border-white/10 py-5"><div className="flex gap-3"><Award className="mt-0.5 h-5 w-5 shrink-0 text-amber-300"/><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Credencial acreditadora</p><p className="mt-2 text-sm font-semibold leading-6">{p.credential}</p></div></div></div>
        <p className="text-sm leading-7 text-slate-400">{p.experience}</p><div className="mt-auto flex gap-3 pt-7">{p.email&&<a href={`mailto:${p.email}`} className="flex h-10 w-10 items-center justify-center border border-white/15 hover:border-amber-300 hover:text-amber-300"><Mail className="h-4 w-4"/></a>}{p.linkedin&&<a href={p.linkedin} target="_blank" rel="noreferrer" className="flex h-10 w-10 items-center justify-center border border-white/15 hover:border-amber-300 hover:text-amber-300"><Linkedin className="h-4 w-4"/></a>}</div></div>
      </div></article>)}</div>
  </div>
</section>;
export default Team;
